### ISSUE TITLE
Enhancement - Legend for Mazes and ...

### ISSUE THREAD

**Issue by NoralK** [dmolony/MazeWalker#1]
Greetings,

Thank you for a wonderful tool.

It would be lovely to have a legend of what the different colors/symbols are for the mazes.

Do you have any plans on making this an editor as well?  It would make modding so much easier, Wizard's Workbench is frustrating to use.

Cheers
Noral

**Comment by dmolony** [comment]
Hi

The colours and symbols probably aren't final yet. It was always intended to make this an editor as well, but I'm currently working on other projects so it will be a while.

Glad you find it useful.
