### ISSUE TITLE
Character Possession Cursed Flag

### ISSUE THREAD

**Issue by n00beh** [dmolony/MazeWalker#2]
Hi there, first of all I want to congratulate you on the wonderful job you did of making this WizardryApp!    Mighty impressive!  I am using it to extract data from the Proving Grounds scenario disk.  I have run into a small bug with the Character's Possession Cursed flag.  When Wizardry saves this to disk, I am seeing FFFF in this field for -1 in the SCENARIO.DATA file.  However, your Character class is looking for a value of 1.  Looking through the Wizardry source from Thomas Ewers, I can't find where TRUE evaluates to -1 for that field, however it is there on the disk.  Can you verify this?

**Comment by dmolony** [comment]
Hi, I'm glad it's useful to you.

For questions about the wizardry source, your best bet would be https://www.zimlab.com/wizardry/
